### ISSUE TITLE
I have a Dreo Smart Pedestal Circulator Fan Model DR-HAOO3S

### ISSUE THREAD

**Issue by Grapplerone** [zyonse/homebridge-dreo#31]
Works with fan speed. Oscilate Horizontally (on/off) only via scene or automation. Has a temperature sensor with temp.

**Describe Your Problem:**
There is no oscilate control in main fan control or any vertical oscillate control anywhere. Also NO TURBO fan speed.

I could not find a way to contact you like you asked if I had another fan that works or not. You don't have an email.

**Comment by zyonse** [comment]
Thanks, I just updated the readme with your model. You should be able to control the oscillation if you go Device settings > Accessories > Fan > Settings. See updated readme images for a better visual representation. If you have the temperature sensor enabled it makes the layout a bit more complicated and it's not something we really have control over on the device side.

[HomeKit](https://developers.homebridge.io/#/service/Fanv2) doesn't support turbo mode or vertical oscillation so there aren't any plans to support those at this time.

**Comment by Grapplerone** [comment]
Odd I didn’t see the ocillation but thanks.Note: Model DR-HAF003S (which I misspelled) but looks like you figured that out. However, this is a PEDESTAL fan not table fan.Sent from my iPhoneOn Jan 3, 2024, at 12:39 PM, Gavin Zyonse ***@***.***> wrote:﻿
Thanks, I just updated the readme with your model. You should be able to control the oscillation if you go Device settings > Accessories > Fan > Settings. See updated readme images for a better visual representation. If you have the temperature sensor enabled it makes the layout a bit more complicated and it's not something we really have control over on the device side.
HomeKit doesn't support turbo mode or vertical oscillation so there aren't any plans to support those at this time.

**Comment by zyonse** [comment]
Oscillation is still missing? Can you send a screenshot of the settings page I referenced above?

**Comment by Grapplerone** [comment]
Yes it’s there, I just failed to find it the first time I asked.And this model (HAF003S) is actually a PEDESTAL fan, not a table fan.Sent from my iPhoneOn Jan 4, 2024, at 10:51 AM, Gavin Zyonse ***@***.***> wrote:﻿
Oscillation is still missing? Can you send a screenshot of the settings page I referenced above?

**Comment by zyonse** [comment]
@Grapplerone Can you let me know if it's still working with v3.2.5? I made some critical changes that might break it since the device isn't a traditional tower fan.

**Comment by Grapplerone** [comment]
I just updated it and yes it’s working fine.Sent from my iPhoneOn Feb 5, 2024, at 8:10 PM, Gavin Zyonse ***@***.***> wrote:﻿
@Grapplerone Can you let me know if it's still working with v3.2.5? I made some critical changes that might break it since the device isn't a traditional tower fan.
